language: ruby

before_install:
  - gem install bundler
  - gem update bundler

rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0

deploy:
  provider: rubygems
  api_key: $RUBYGEMS_TOKEN
  gem: simple_hubspot

sudo: false
